name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
- name: Setup PHP Action
  uses: shivammathur/setup-php@1.11.7
  with:
    # Setup PHP version.
    php-version: # default is 7.4
    # Setup PHP extensions.
    extensions: # optional
    # Add values to php.ini.
    ini-values: # optional
    # Setup code coverage driver.
    coverage: # optional
    # Setup PECL on ubuntu
    pecl: # optional
    # Deprecated! Use extensions instead.
    extension-csv: # optional
    # Deprecated! Use ini-values instead.
    ini-values-csv: # optional
